name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare standalone
        run: |
          mkdir build
          cp -r .next/standalone/* build/

      - name: Archive
        run: tar -czf build.tar.gz build

      - name: Upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build.tar.gz"
          target: "/root"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.bashrc || source ~/.profile
            rm -rf /root/app
            mkdir /root/app

            tar -xzf /root/build.tar.gz -C /root/app
            rm /root/build.tar.gz

            cp /root/frona/.env /root/app/build/.env

            cd /root/app/build

            pm2 delete dashboard || true
            pm2 start server.js --name dashboard

            pm2 save